/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.softsec.tase.common.rpc.domain.job;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * job priority enumeration
 */
public enum JobPriority implements org.apache.thrift.TEnum {
  HIGHER(1),
  HIGH(2),
  MEDIUM(3),
  LOW(4),
  LOWER(5);

  private final int value;

  private JobPriority(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static JobPriority findByValue(int value) { 
    switch (value) {
      case 1:
        return HIGHER;
      case 2:
        return HIGH;
      case 3:
        return MEDIUM;
      case 4:
        return LOW;
      case 5:
        return LOWER;
      default:
        return null;
    }
  }
}
