/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.softsec.tase.common.rpc.domain.job;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * job status enumeration
 */
public enum JobStatus implements org.apache.thrift.TEnum {
  COMMITTED(0),
  SCHEDULED(1),
  ISSUE_FAILED(2),
  ISSUED(3),
  RUNNING(4),
  INTERRUPTED(5),
  KILLED(6),
  TIMEOUT(7),
  FAILURE(8),
  FINISHED(9);

  private final int value;

  private JobStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static JobStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return COMMITTED;
      case 1:
        return SCHEDULED;
      case 2:
        return ISSUE_FAILED;
      case 3:
        return ISSUED;
      case 4:
        return RUNNING;
      case 5:
        return INTERRUPTED;
      case 6:
        return KILLED;
      case 7:
        return TIMEOUT;
      case 8:
        return FAILURE;
      case 9:
        return FINISHED;
      default:
        return null;
    }
  }
}
