/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.softsec.tase.common.rpc.domain.app;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * app file status enumeration
 */
public enum FileStatus implements org.apache.thrift.TEnum {
  EVALUATED(0),
  STATICED(1),
  DYNAMICED(2),
  PACKAGED(3),
  DEPLOYED(4);

  private final int value;

  private FileStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static FileStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return EVALUATED;
      case 1:
        return STATICED;
      case 2:
        return DYNAMICED;
      case 3:
        return PACKAGED;
      case 4:
        return DEPLOYED;
      default:
        return null;
    }
  }
}
