/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.softsec.tase.common.rpc.domain.container;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum BundleType implements org.apache.thrift.TEnum {
  ZIP(1),
  JAR(2);

  private final int value;

  private BundleType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static BundleType findByValue(int value) { 
    switch (value) {
      case 1:
        return ZIP;
      case 2:
        return JAR;
      default:
        return null;
    }
  }
}
